// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbnFCQumDaCGRgi9A5c0aX1ym37xftABQ',
    appId: '1:253061783930:web:8a0d3cc3b119c3685436c3',
    messagingSenderId: '253061783930',
    projectId: 'ecom-a756e',
    authDomain: 'ecom-a756e.firebaseapp.com',
    storageBucket: 'ecom-a756e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ImrdBnQvr2RB6DdfJGiXTNIJlMQy6TU',
    appId: '1:253061783930:android:6f12ebe6580fbed55436c3',
    messagingSenderId: '253061783930',
    projectId: 'ecom-a756e',
    storageBucket: 'ecom-a756e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbX5LCu0_QsNx7gklnABevllTE6lT-W4',
    appId: '1:253061783930:ios:872b8efcb63d3b2a5436c3',
    messagingSenderId: '253061783930',
    projectId: 'ecom-a756e',
    storageBucket: 'ecom-a756e.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPbX5LCu0_QsNx7gklnABevllTE6lT-W4',
    appId: '1:253061783930:ios:872b8efcb63d3b2a5436c3',
    messagingSenderId: '253061783930',
    projectId: 'ecom-a756e',
    storageBucket: 'ecom-a756e.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbnFCQumDaCGRgi9A5c0aX1ym37xftABQ',
    appId: '1:253061783930:web:6083dd285e7e4fc15436c3',
    messagingSenderId: '253061783930',
    projectId: 'ecom-a756e',
    authDomain: 'ecom-a756e.firebaseapp.com',
    storageBucket: 'ecom-a756e.firebasestorage.app',
  );
}
